apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jifr7698q-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jifr7698q-go 
  name: jifr7698q-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jifr7698q-go 
